In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
data = pd.read_csv('../../data/g-research-crypto-forecasting/train.csv')
data['timestamp'] = pd.to_datetime(data['timestamp'], unit='s')
data.head()

,timestamp,Asset_ID,Count,Open,High,Low,Close,Volume,VWAP,Target
0,2018-01-01 00:01:00,2,40.0,2376.5800,2399.5000,2357.1400,2374.5900,19.233005,2373.116392,-0.004218
1,2018-01-01 00:01:00,0,5.0,8.5300,8.5300,8.5300,8.5300,78.380000,8.530000,-0.014399
2,2018-01-01 00:01:00,1,229.0,13835.1940,14013.8000,13666.1100,13850.1760,31.550062,13827.062093,-0.014643
3,2018-01-01 00:01:00,5,32.0,7.6596,7.6596,7.6567,7.6576,6626.713370,7.657713,-0.013922
4,2018-01-01 00:01:00,7,5.0,25.9200,25.9200,25.8740,25.8770,121.087310,25.891363,-0.008264

In [3]:
'''
timestamp - A timestamp for the minute covered by the row.
Asset_ID - An ID code for the cryptoasset.
Count - The number of trades that took place this minute.
Open - The USD price at the beginning of the minute.
High - The highest USD price during the minute.
Low - The lowest USD price during the minute.
Close - The USD price at the end of the minute.
Volume - The number of cryptoasset units traded during the minute.
VWAP - The volume weighted average price for the minute.
Target - 15 minute residualized returns. See the 'Prediction and Evaluation' section of this notebook for details of how the target is calculated.
'''

"\ntimestamp - A timestamp for the minute covered by the row.\nAsset_ID - An ID code for the cryptoasset.\nCount - The number of trades that took place this minute.\nOpen - The USD price at the beginning of the minute.\nHigh - The highest USD price during the minute.\nLow - The lowest USD price during the minute.\nClose - The USD price at the end of the minute.\nVolume - The number of cryptoasset units traded during the minute.\nVWAP - The volume weighted average price for the minute.\nTarget - 15 minute residualized returns. See the 'Prediction and Evaluation' section of this notebook for details of how the target is calculated.\n"

In [4]:
sorted(data['Asset_ID'].unique())

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13]

In [5]:
data.describe()

,Asset_ID,Count,Open,High,Low,Close,Volume,VWAP,Target
count,2.423681e+07,2.423681e+07,2.423681e+07,2.423681e+07,2.423681e+07,2.423681e+07,2.423681e+07,2.423680e+07,2.348647e+07
mean,6.292544e+00,2.864593e+02,1.432640e+03,1.436350e+03,1.429568e+03,1.432640e+03,2.868530e+05,NaN,7.121752e-06
std,4.091861e+00,8.673982e+02,6.029605e+03,6.039482e+03,6.020261e+03,6.029611e+03,2.433935e+06,NaN,5.679042e-03
min,0.000000e+00,1.000000e+00,1.170400e-03,1.195000e-03,2.000000e-04,1.171400e-03,-3.662812e-01,-inf,-5.093509e-01
25%,3.000000e+00,1.900000e+01,2.676500e-01,2.681600e-01,2.669000e-01,2.676483e-01,1.410725e+02,2.676368e-01,-1.694354e-03
50%,6.000000e+00,6.400000e+01,1.428860e+01,1.431250e+01,1.426300e+01,1.428920e+01,1.295415e+03,1.428769e+01,-4.289844e-05
75%,9.000000e+00,2.210000e+02,2.288743e+02,2.293000e+02,2.284200e+02,2.288729e+02,2.729764e+04,2.288728e+02,1.601520e-03
max,1.300000e+01,1.650160e+05,6.480594e+04,6.490000e+04,6.467053e+04,6.480854e+04,7.597554e+08,inf,9.641699e-01

In [6]:
asset_details = pd.read_csv('../../data/g-research-crypto-forecasting/asset_details.csv')
id_to_names = dict(zip(asset_details['Asset_ID'], asset_details['Asset_Name']))

In [7]:
data['Asset_Name'] = [id_to_names[a] for a in data['Asset_ID']]

In [12]:
id_to_names

{2: 'Bitcoin Cash',
 0: 'Binance Coin',
 1: 'Bitcoin',
 5: 'EOS.IO',
 7: 'Ethereum Classic',
 6: 'Ethereum',
 9: 'Litecoin',
 11: 'Monero',
 13: 'TRON',
 12: 'Stellar',
 3: 'Cardano',
 8: 'IOTA',
 10: 'Maker',
 4: 'Dogecoin'}

In [8]:
data.sort_values(['timestamp', 'Asset_ID'], inplace=True)
data.set_index(['timestamp', 'Asset_ID'])

                              Count          Open          High           Low  \
timestamp           Asset_ID
2018-01-01 00:01:00 0           5.0      8.530000      8.530000      8.530000
                    1         229.0  13835.194000  14013.800000  13666.110000
                    2          40.0   2376.580000   2399.500000   2357.140000
                    5          32.0      7.659600      7.659600      7.656700
                    6         173.0    738.302500    746.000000    732.510000
...                             ...           ...           ...           ...
2021-09-21 00:00:00 9         775.0    157.181571    157.250000    156.700000
                    10         34.0   2437.065067   2438.000000   2430.226900
                    11         48.0    232.695000    232.800000    232.240000
                    12        177.0      0.282168      0.282438      0.281842
                    13        380.0      0.091390      0.091527      0.091260

                                     Close        Volume          VWAP  \
timestamp           Asset_ID
2018-01-01 00:01:00 0             8.530000  7.838000e+01      8.530000
                    1         13850.176000  3.155006e+01  13827.062093
                    2          2374.590000  1.923301e+01   2373.116392
                    5             7.657600  6.626713e+03      7.657713
                    6           738.507500  3.359879e+02    738.839291
...                                    ...           ...           ...
2021-09-21 00:00:00 9           156.943857  4.663725e+03    156.994319
                    10         2432.907467  3.975460e+00   2434.818747
                    11          232.275000  1.035123e+02    232.569697
                    12            0.282051  1.828508e+05      0.282134
                    13            0.091349  2.193732e+06      0.091388

                                Target    Asset_Name
timestamp           Asset_ID
2018-01-01 00:01:00 0        -0.014399  Binance Coin
                    1        -0.014643       Bitcoin
                    2        -0.004218  Bitcoin Cash
                    5        -0.013922        EOS.IO
                    6        -0.004809      Ethereum
...                                ...           ...
2021-09-21 00:00:00 9              NaN      Litecoin
                    10             NaN         Maker
                    11             NaN        Monero
                    12             NaN       Stellar
                    13             NaN          TRON

[24236806 rows x 9 columns]

In [9]:
data[['Close', 'Low', 'High']]

                 Close           Low          High
1             8.530000      8.530000      8.530000
2         13850.176000  13666.110000  14013.800000
0          2374.590000   2357.140000   2399.500000
3             7.657600      7.656700      7.659600
5           738.507500    732.510000    746.000000
...                ...           ...           ...
24236801    156.943857    156.700000    157.250000
24236802   2432.907467   2430.226900   2438.000000
24236805    232.275000    232.240000    232.800000
24236804      0.282051      0.281842      0.282438
24236803      0.091349      0.091260      0.091527

[24236806 rows x 3 columns]

In [40]:
close_by_asset = []
for asset_id in range(14):
    tmp = data[data['Asset_ID'] == asset_id].set_index('timestamp')
    close_by_asset.append(tmp['Close'])

In [41]:
close_by_asset = pd.concat(close_by_asset, axis=1)
close_by_asset.columns = [id_to_names[i] for i in range(14)]

In [42]:
log_returns_by_asset = np.log(close_by_asset) - np.log(close_by_asset.shift(1))

In [43]:
log_returns_by_asset

,Binance Coin,Bitcoin,Bitcoin Cash,Cardano,Dogecoin,EOS.IO,Ethereum,Ethereum Classic,IOTA,Litecoin,Maker,Monero,Stellar,TRON
timestamp,,,,,,,,,,,,,,
2018-01-01 00:01:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2018-01-01 00:02:00,-0.001819,-0.001595,-0.000970,NaN,NaN,-0.000118,-0.000335,0.000773,NaN,-0.001555,NaN,-0.000030,NaN,NaN
2018-01-01 00:03:00,-0.003494,-0.001939,-0.000094,NaN,NaN,-0.000719,-0.001027,0.021866,NaN,0.005072,NaN,-0.000790,NaN,NaN
2018-01-01 00:04:00,0.001896,-0.002414,-0.000631,NaN,NaN,-0.002015,-0.000543,-0.000756,NaN,-0.007662,NaN,-0.003134,NaN,NaN
2018-01-01 00:05:00,-0.005296,-0.003137,-0.000166,NaN,NaN,-0.003385,-0.001898,-0.000473,NaN,-0.002031,NaN,-0.002227,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2021-09-20 23:56:00,-0.003282,-0.002007,-0.002363,-0.007796,-0.003144,-0.003516,-0.003137,-0.001912,-0.004869,-0.002359,-0.003641,-0.002766,-0.003261,-0.002754
2021-09-20 23:57:00,-0.001980,-0.000910,-0.005945,-0.000610,-0.002531,-0.002115,-0.001305,-0.004158,-0.002737,-0.003906,-0.002640,-0.003065,-0.002748,-0.003939
2021-09-20 23:58:00,-0.000945,-0.000770,0.000158,-0.000583,-0.000596,-0.000822,-0.001165,-0.001059,-0.001528,-0.001038,0.000692,-0.000551,-0.002100,-0.000041
2021-09-20 23:59:00,0.006217,0.004433,0.006913,0.007448,0.008783,0.005493,0.006670,0.005138,0.007462,0.005811,0.005988,0.004771,0.005839,0.005122
2021-09-21 00:00:00,-0.000981,-0.000343,-0.002709,-0.000514,-0.001569,-0.000713,-0.001542,-0.000206,-0.001558,-0.001790,-0.001128,0.000073,-0.000095,0.000253

In [ ]:
sns.set_style('darkgrid')
sns.set_context('paper')
fig = plt.figure(figsize=(8, 6))
sns.heatmap(log_returns_by_asset.corr(), cmap='viridis') # gist_earth
plt.title('Correlation of Log-Returns')
plt.savefig('../../figures/correlation.pdf')
plt.show()

In [9]:
# test_idx = 
# data.set_index(['timestamp', 'Asset_ID']).loc[data['timestamp'].min()].values
# data.set_index(['timestamp', 'Asset_ID'])['Target']

array([[5.0, 8.53, 8.53, 8.53, 8.53, 78.38, 8.53, -0.0143989664689647,
        'Binance Coin'],
       [229.0, 13835.194, 14013.8, 13666.11, 13850.176, 31.55006152,
        13827.062092689885, -0.0146432243557361, 'Bitcoin'],
       [40.0, 2376.58, 2399.5, 2357.14, 2374.59, 19.23300519,
        2373.1163915061647, -0.0042181523874292, 'Bitcoin Cash'],
       [32.0, 7.6596, 7.6596, 7.6567, 7.6576, 6626.713369870001,
        7.657712894055892, -0.0139224470071963, 'EOS.IO'],
       [173.0, 738.3025, 746.0, 732.51, 738.5075, 335.98785619,
        738.839291493523, -0.0048086040148456, 'Ethereum'],
       [5.0, 25.92, 25.92, 25.874, 25.877, 121.08731, 25.89136300520674,
        -0.0082635054253386, 'Ethereum Classic'],
       [167.0, 225.33, 227.78, 222.98, 225.20666666666668, 411.89664234,
        225.1979435524601, -0.0097914226840802, 'Litecoin'],
       [7.0, 329.09, 329.88, 329.09, 329.46, 6.63571014,
        329.4541176122712, nan, 'Monero']], dtype=object)

In [11]:
data.isnull().sum() / len(data)

timestamp     0.000000e+00
Asset_ID      0.000000e+00
Count         0.000000e+00
Open          0.000000e+00
High          0.000000e+00
Low           0.000000e+00
Close         0.000000e+00
Volume        0.000000e+00
VWAP          3.713361e-07
Target        3.095862e-02
Asset_Name    0.000000e+00
dtype: float64

In [12]:
data.fillna(method='ffill', inplace=True)
data.fillna(value=0, inplace=True)

In [13]:
data.head()

,timestamp,Asset_ID,Count,Open,High,Low,Close,Volume,VWAP,Target,Asset_Name
1,2018-01-01 00:01:00,0,5.0,8.5300,8.5300,8.5300,8.5300,78.380000,8.530000,-0.014399,Binance Coin
2,2018-01-01 00:01:00,1,229.0,13835.1940,14013.8000,13666.1100,13850.1760,31.550062,13827.062093,-0.014643,Bitcoin
0,2018-01-01 00:01:00,2,40.0,2376.5800,2399.5000,2357.1400,2374.5900,19.233005,2373.116392,-0.004218,Bitcoin Cash
3,2018-01-01 00:01:00,5,32.0,7.6596,7.6596,7.6567,7.6576,6626.713370,7.657713,-0.013922,EOS.IO
5,2018-01-01 00:01:00,6,173.0,738.3025,746.0000,732.5100,738.5075,335.987856,738.839291,-0.004809,Ethereum

In [14]:
import torch
from torch.utils.data import Dataset, IterableDataset, DataLoader

In [15]:
class CryptoFeed(Dataset):
    def __init__(self, df, technicals=None):
        """
        Args:
            df: pandas Dataframe, contains price data on crypto assets. Assumes 
            technicals: dict, string (key) mapped to function (value) that calculates technical indicator from df
        """
        df.sort_values(['timestamp', 'Asset_ID'], inplace=True)
        
        self.features = df.copy()
        if technicals is not None:
            for k, v in technicals.items():
                self.features[k] = v(df)
        self.features.set_index(['timestamp', 'Asset_ID'], inplace=True)
        for col in ['timestamp', 'Asset_ID', 'Asset_Name', 'Target']:
            if col in self.features.columns:
                self.features.drop(col, axis=1, inplace=True)
                
        self.targets = df.set_index(['timestamp', 'Asset_ID'])['Target']
        self.index_to_date = dict(zip(range(len(df['timestamp'].unique)), sorted(df['timestamp'].unique())))
    
    def __len__(self):
        return self.df.shape[0]
    
    def __getitem__(self, idx):
        date = self.index_to_date[idx]
        return self.features.loc[date].values, self.targets.loc[date].values

In [16]:
class CryptoFeed(IterableDataset):
    def __init__(self, df, seq_len=5, technicals=None):
        """
        Creates an iterable feed of crypto market states increasing in time given an input df

        Args:
            df: pandas Dataframe, contains price data on crypto assets. Assumes 
            technicals: dict, string (key) mapped to function (value) that calculates technical indicator from df
        """
        df.sort_values(['timestamp', 'Asset_ID'], inplace=True)
        
        self.id_to_name = dict(zip(df['Asset_ID'], df['Asset_Name']))
        self.data = [df[df['Asset_ID'] == i].copy() for i in sorted(df['Asset_ID'].unique())]
        self.targets = pd.concat([tdf.set_index('timestamp')['Target'] for tdf in self.data], axis=1)

        if technicals is not None:
            for tdf in self.data:
                for k, v in technicals.items():
                    tdf[k] = v(tdf)
        for tdf in self.data:
            tdf.set_index('timestamp', inplace=True)
        for col in ['timestamp', 'Asset_ID', 'Asset_Name', 'Target']:
            for tdf in self.data:
                if col in tdf.columns:
                    tdf.drop(col, axis=1, inplace=True)

        self.features = pd.concat(self.data, axis=1)
                        
        self.seq_len = seq_len
        self.valid_dates = list(self.features.index)
        # self.num_valid_starts = self.features.shape[0] - self.seq_len
    
    def __len__(self):
        return self.features.shape[0]
    
    def __iter__(self):
        for i in range(self.seq_len, len(self.valid_dates)):
            dates_idx = self.valid_dates[i-self.seq_len:i]
            features = self.features.loc[dates_idx].values
            target = self.targets.loc[dates_idx[-1]].values # target is target of end of window
            adj = self.targets.loc[dates_idx].corr().values # correlation matrix between previous seq_len target values
            print(self.targets.loc[dates_idx])
            print(self.targets.loc[dates_idx].corr())
            print(adj)
            yield features, target, adj

In [17]:
dataset = CryptoFeed(data)

In [18]:
dataloader = DataLoader(dataset)

In [19]:
i = 0
for x, y, a in dataloader:
    if i > 2:
        break
    print(x.shape, y.shape, a.shape)
    i += 1

                       Target    Target    Target  Target  Target    Target  \
timestamp
2018-01-01 00:01:00 -0.014399 -0.014643 -0.004218     NaN     NaN -0.013922
2018-01-01 00:02:00 -0.015875 -0.015037 -0.004079     NaN     NaN -0.014534
2018-01-01 00:03:00 -0.015410 -0.010309 -0.002892     NaN     NaN -0.012546
2018-01-01 00:04:00 -0.012524 -0.008999 -0.003718     NaN     NaN -0.011170
2018-01-01 00:05:00 -0.005940 -0.008079 -0.002171     NaN     NaN -0.006154

                       Target    Target  Target    Target  Target    Target  \
timestamp
2018-01-01 00:01:00 -0.004809 -0.008264     NaN -0.009791     NaN -0.009791
2018-01-01 00:02:00 -0.004441 -0.029902     NaN -0.012991     NaN -0.009690
2018-01-01 00:03:00 -0.004206 -0.030832     NaN -0.003572     NaN  0.006567
2018-01-01 00:04:00 -0.002205 -0.028899     NaN -0.002556     NaN -0.007299
2018-01-01 00:05:00 -0.001744 -0.030909     NaN  0.000531     NaN -0.010619

                     Target  Target
timestamp
2018-01-01 00:01:00     NaN     NaN
2018-01-01 00:02:00     NaN     NaN
2018-01-01 00:03:00     NaN     NaN
2018-01-01 00:04:00     NaN     NaN
2018-01-01 00:05:00     NaN     NaN
          Target    Target    Target  Target  Target    Target    Target  \
Target  1.000000  0.704583  0.740358     NaN     NaN  0.969877  0.845066
Target  0.704583  1.000000  0.803980     NaN     NaN  0.839950  0.874815
Target  0.740358  0.803980  1.000000     NaN     NaN  0.860359  0.638492
Target       NaN       NaN       NaN     NaN     NaN       NaN       NaN
Target       NaN       NaN       NaN     NaN     NaN       NaN       NaN
Target  0.969877  0.839950  0.860359     NaN     NaN  1.000000  0.885420
Target  0.845066  0.874815  0.638492     NaN     NaN  0.885420  1.000000
Target -0.239515 -0.566629 -0.570746     NaN     NaN -0.404314 -0.518534
Target       NaN       NaN       NaN     NaN     NaN       NaN       NaN
Target  0.743731  0.981439  0.834654     NaN     NaN  0.864802  0.827105
Target       NaN       NaN       NaN     NaN     NaN       NaN       NaN
Target -0.404421  0.224581  0.268207     NaN     NaN -0.186572 -0.252179
Target       NaN       NaN       NaN     NaN     NaN       NaN       NaN
Target       NaN       NaN       NaN     NaN     NaN       NaN       NaN

          Target  Target    Target  Target    Target  Target  Target
Target -0.239515     NaN  0.743731     NaN -0.404421     NaN     NaN
Target -0.566629     NaN  0.981439     NaN  0.224581     NaN     NaN
Target -0.570746     NaN  0.834654     NaN  0.268207     NaN     NaN
Target       NaN     NaN       NaN     NaN       NaN     NaN     NaN
Target       NaN     NaN       NaN     NaN       NaN     NaN     NaN
Target -0.404314     NaN  0.864802     NaN -0.186572     NaN     NaN
Target -0.518534     NaN  0.827105     NaN -0.252179     NaN     NaN
Target  1.000000     NaN -0.432113     NaN -0.306444     NaN     NaN
Target       NaN     NaN       NaN     NaN       NaN     NaN     NaN
Target -0.432113     NaN  1.000000     NaN  0.226497     NaN     NaN
Target       NaN     NaN       NaN     NaN       NaN     NaN     NaN
Target -0.306444     NaN  0.226497     NaN  1.000000     NaN     NaN
Target       NaN     NaN       NaN     NaN       NaN     NaN     NaN
Target       NaN     NaN       NaN     NaN       NaN     NaN     NaN
[[ 1.          0.70458331  0.7403578          nan         nan  0.96987689
   0.84506567 -0.23951522         nan  0.74373128         nan -0.40442126
          nan         nan]
 [ 0.70458331  1.          0.80398044         nan         nan  0.83994986
   0.87481473 -0.56662874         nan  0.9814387          nan  0.22458108
          nan         nan]
 [ 0.7403578   0.80398044  1.                 nan         nan  0.86035911
   0.63849235 -0.57074608         nan  0.8346536          nan  0.26820667
          nan         nan]
 [        nan         nan         nan         nan         nan         nan
          nan         nan         nan         nan         nan         nan
          nan         nan]
 [        nan         nan         nan         nan         nan         nan
          nan         nan         nan         nan         nan         nan
          nan         nan]
 [ 0.96987689  0.83994986  0.86035911         nan         nan  1.
   0.88541971 -0.40431439         nan  0.86480188         nan -0.18657172
          nan         nan]
 [ 0.84506567  0.87481473  0.63849235         nan         nan  0.88541971
   1.         -0.51853426         nan  0.8271054          nan -0.25217949
          nan         nan]
 [-0.23951522 -0.56662874 -0.57074608         nan         nan -0.40431439
  -0.51853426  1.                 nan -0.43211326         nan -0.30644384
          nan         nan]
 [        nan         nan         nan         nan         nan         nan
          nan         nan         nan         nan         nan         nan
          nan         nan]
 [ 0.74373128  0.9814387   0.8346536          nan         nan  0.86480188
   0.8271054  -0.43211326         nan  1.                 nan  0.22649723
          nan         nan]
 [        nan         nan         nan         nan         nan         nan
          nan         nan         nan         nan         nan         nan
          nan         nan]
 [-0.40442126  0.22458108  0.26820667         nan         nan -0.18657172
  -0.25217949 -0.30644384         nan  0.22649723         nan  1.
          nan         nan]
 [        nan         nan         nan         nan         nan         nan
          nan         nan         nan         nan         nan         nan
          nan         nan]
 [        nan         nan         nan         nan         nan         nan
          nan         nan         nan         nan         nan         nan
          nan         nan]]
torch.Size([1, 5, 98]) torch.Size([1, 14]) torch.Size([1, 14, 14])
                       Target    Target    Target  Target  Target    Target  \
timestamp
2018-01-01 00:02:00 -0.015875 -0.015037 -0.004079     NaN     NaN -0.014534
2018-01-01 00:03:00 -0.015410 -0.010309 -0.002892     NaN     NaN -0.012546
2018-01-01 00:04:00 -0.012524 -0.008999 -0.003718     NaN     NaN -0.011170
2018-01-01 00:05:00 -0.005940 -0.008079 -0.002171     NaN     NaN -0.006154
2018-01-01 00:06:00 -0.005455 -0.004422 -0.009202     NaN     NaN -0.008654

                       Target    Target  Target    Target  Target    Target  \
timestamp
2018-01-01 00:02:00 -0.004441 -0.029902     NaN -0.012991     NaN -0.009690
2018-01-01 00:03:00 -0.004206 -0.030832     NaN -0.003572     NaN  0.006567
2018-01-01 00:04:00 -0.002205 -0.028899     NaN -0.002556     NaN -0.007299
2018-01-01 00:05:00 -0.001744 -0.030909     NaN  0.000531     NaN -0.010619
2018-01-01 00:06:00 -0.001331 -0.001331     NaN -0.002572     NaN  0.005323

                     Target  Target
timestamp
2018-01-01 00:02:00     NaN     NaN
2018-01-01 00:03:00     NaN     NaN
2018-01-01 00:04:00     NaN     NaN
2018-01-01 00:05:00     NaN     NaN
2018-01-01 00:06:00     NaN     NaN
          Target    Target    Target  Target  Target    Target    Target  \
Target  1.000000  0.838597 -0.438721     NaN     NaN  0.933909  0.921410
Target  0.838597  1.000000 -0.557864     NaN     NaN  0.776657  0.878077
Target -0.438721 -0.557864  1.000000     NaN     NaN -0.110169 -0.433800
Target       NaN       NaN       NaN     NaN     NaN       NaN       NaN
Target       NaN       NaN       NaN     NaN     NaN       NaN       NaN
Target  0.933909  0.776657 -0.110169     NaN     NaN  1.000000  0.867296
Target  0.921410  0.878077 -0.433800     NaN     NaN  0.867296  1.000000
Target  0.602674  0.710886 -0.974810     NaN     NaN  0.310722  0.570486
Target       NaN       NaN       NaN     NaN     NaN       NaN       NaN
Target  0.680706  0.809602  0.034635     NaN     NaN  0.839675  0.740917
Target       NaN       NaN       NaN     NaN     NaN       NaN       NaN
Target  0.026821  0.453906 -0.510307     NaN     NaN -0.068344 -0.017249
Target       NaN       NaN       NaN     NaN     NaN       NaN       NaN
Target       NaN       NaN       NaN     NaN     NaN       NaN       NaN

          Target  Target    Target  Target    Target  Target  Target
Target  0.602674     NaN  0.680706     NaN  0.026821     NaN     NaN
Target  0.710886     NaN  0.809602     NaN  0.453906     NaN     NaN
Target -0.974810     NaN  0.034635     NaN -0.510307     NaN     NaN
Target       NaN     NaN       NaN     NaN       NaN     NaN     NaN
Target       NaN     NaN       NaN     NaN       NaN     NaN     NaN
Target  0.310722     NaN  0.839675     NaN -0.068344     NaN     NaN
Target  0.570486     NaN  0.740917     NaN -0.017249     NaN     NaN
Target  1.000000     NaN  0.164861     NaN  0.544916     NaN     NaN
Target       NaN     NaN       NaN     NaN       NaN     NaN     NaN
Target  0.164861     NaN  1.000000     NaN  0.204385     NaN     NaN
Target       NaN     NaN       NaN     NaN       NaN     NaN     NaN
Target  0.544916     NaN  0.204385     NaN  1.000000     NaN     NaN
Target       NaN     NaN       NaN     NaN       NaN     NaN     NaN
Target       NaN     NaN       NaN     NaN       NaN     NaN     NaN
[[ 1.          0.83859677 -0.43872115         nan         nan  0.93390908
   0.92141006  0.6026738          nan  0.68070579         nan  0.0268206
          nan         nan]
 [ 0.83859677  1.         -0.5578636          nan         nan  0.77665684
   0.87807697  0.71088571         nan  0.80960204         nan  0.45390629
          nan         nan]
 [-0.43872115 -0.5578636   1.                 nan         nan -0.11016892
  -0.43379978 -0.9748098          nan  0.03463528         nan -0.51030662
          nan         nan]
 [        nan         nan         nan         nan         nan         nan
          nan         nan         nan         nan         nan         nan
          nan         nan]
 [        nan         nan         nan         nan         nan         nan
          nan         nan         nan         nan         nan         nan
          nan         nan]
 [ 0.93390908  0.77665684 -0.11016892         nan         nan  1.
   0.86729627  0.31072154         nan  0.83967524         nan -0.06834418
          nan         nan]
 [ 0.92141006  0.87807697 -0.43379978         nan         nan  0.86729627
   1.          0.57048579         nan  0.74091744         nan -0.017249
          nan         nan]
 [ 0.6026738   0.71088571 -0.9748098          nan         nan  0.31072154
   0.57048579  1.                 nan  0.16486102         nan  0.54491643
          nan         nan]
 [        nan         nan         nan         nan         nan         nan
          nan         nan         nan         nan         nan         nan
          nan         nan]
 [ 0.68070579  0.80960204  0.03463528         nan         nan  0.83967524
   0.74091744  0.16486102         nan  1.                 nan  0.20438528
          nan         nan]
 [        nan         nan         nan         nan         nan         nan
          nan         nan         nan         nan         nan         nan
          nan         nan]
 [ 0.0268206   0.45390629 -0.51030662         nan         nan -0.06834418
  -0.017249    0.54491643         nan  0.20438528         nan  1.
          nan         nan]
 [        nan         nan         nan         nan         nan         nan
          nan         nan         nan         nan         nan         nan
          nan         nan]
 [        nan         nan         nan         nan         nan         nan
          nan         nan         nan         nan         nan         nan
          nan         nan]]
torch.Size([1, 5, 98]) torch.Size([1, 14]) torch.Size([1, 14, 14])
                       Target    Target    Target  Target  Target    Target  \
timestamp
2018-01-01 00:03:00 -0.015410 -0.010309 -0.002892     NaN     NaN -0.012546
2018-01-01 00:04:00 -0.012524 -0.008999 -0.003718     NaN     NaN -0.011170
2018-01-01 00:05:00 -0.005940 -0.008079 -0.002171     NaN     NaN -0.006154
2018-01-01 00:06:00 -0.005455 -0.004422 -0.009202     NaN     NaN -0.008654
2018-01-01 00:07:00 -0.000644 -0.008873 -0.004458     NaN     NaN -0.012036

                       Target    Target  Target    Target  Target    Target  \
timestamp
2018-01-01 00:03:00 -0.004206 -0.030832     NaN -0.003572     NaN  0.006567
2018-01-01 00:04:00 -0.002205 -0.028899     NaN -0.002556     NaN -0.007299
2018-01-01 00:05:00 -0.001744 -0.030909     NaN  0.000531     NaN -0.010619
2018-01-01 00:06:00 -0.001331 -0.001331     NaN -0.002572     NaN  0.005323
2018-01-01 00:07:00 -0.002983 -0.026319     NaN -0.003973     NaN  0.000548

                     Target  Target
timestamp
2018-01-01 00:03:00     NaN     NaN
2018-01-01 00:04:00     NaN     NaN
2018-01-01 00:05:00     NaN     NaN
2018-01-01 00:06:00     NaN     NaN
2018-01-01 00:07:00     NaN     NaN
          Target    Target    Target  Target  Target    Target    Target  \
Target  1.000000  0.458382 -0.339849     NaN     NaN  0.324669  0.456559
Target  0.458382  1.000000 -0.872724     NaN     NaN  0.557720  0.809809
Target -0.339849 -0.872724  1.000000     NaN     NaN -0.083075 -0.497584
Target       NaN       NaN       NaN     NaN     NaN       NaN       NaN
Target       NaN       NaN       NaN     NaN     NaN       NaN       NaN
Target  0.324669  0.557720 -0.083075     NaN     NaN  1.000000  0.779452
Target  0.456559  0.809809 -0.497584     NaN     NaN  0.779452  1.000000
Target  0.331863  0.931047 -0.983507     NaN     NaN  0.237209  0.568210
Target       NaN       NaN       NaN     NaN     NaN       NaN       NaN
Target  0.081524  0.214009  0.284082     NaN     NaN  0.921334  0.588374
Target       NaN       NaN       NaN     NaN     NaN       NaN       NaN
Target -0.110434  0.159308 -0.531051     NaN     NaN -0.535958 -0.444553
Target       NaN       NaN       NaN     NaN     NaN       NaN       NaN
Target       NaN       NaN       NaN     NaN     NaN       NaN       NaN

          Target  Target    Target  Target    Target  Target  Target
Target  0.331863     NaN  0.081524     NaN -0.110434     NaN     NaN
Target  0.931047     NaN  0.214009     NaN  0.159308     NaN     NaN
Target -0.983507     NaN  0.284082     NaN -0.531051     NaN     NaN
Target       NaN     NaN       NaN     NaN       NaN     NaN     NaN
Target       NaN     NaN       NaN     NaN       NaN     NaN     NaN
Target  0.237209     NaN  0.921334     NaN -0.535958     NaN     NaN
Target  0.568210     NaN  0.588374     NaN -0.444553     NaN     NaN
Target  1.000000     NaN -0.131018     NaN  0.482768     NaN     NaN
Target       NaN     NaN       NaN     NaN       NaN     NaN     NaN
Target -0.131018     NaN  1.000000     NaN -0.736307     NaN     NaN
Target       NaN     NaN       NaN     NaN       NaN     NaN     NaN
Target  0.482768     NaN -0.736307     NaN  1.000000     NaN     NaN
Target       NaN     NaN       NaN     NaN       NaN     NaN     NaN
Target       NaN     NaN       NaN     NaN       NaN     NaN     NaN
[[ 1.          0.458382   -0.33984923         nan         nan  0.32466878
   0.45655862  0.33186347         nan  0.08152432         nan -0.11043393
          nan         nan]
 [ 0.458382    1.         -0.8727244          nan         nan  0.55772008
   0.80980881  0.93104748         nan  0.21400889         nan  0.15930796
          nan         nan]
 [-0.33984923 -0.8727244   1.                 nan         nan -0.08307547
  -0.49758434 -0.983507           nan  0.28408198         nan -0.53105095
          nan         nan]
 [        nan         nan         nan         nan         nan         nan
          nan         nan         nan         nan         nan         nan
          nan         nan]
 [        nan         nan         nan         nan         nan         nan
          nan         nan         nan         nan         nan         nan
          nan         nan]
 [ 0.32466878  0.55772008 -0.08307547         nan         nan  1.
   0.77945169  0.23720881         nan  0.92133394         nan -0.53595756
          nan         nan]
 [ 0.45655862  0.80980881 -0.49758434         nan         nan  0.77945169
   1.          0.56820991         nan  0.58837402         nan -0.44455348
          nan         nan]
 [ 0.33186347  0.93104748 -0.983507           nan         nan  0.23720881
   0.56820991  1.                 nan -0.1310182          nan  0.48276802
          nan         nan]
 [        nan         nan         nan         nan         nan         nan
          nan         nan         nan         nan         nan         nan
          nan         nan]
 [ 0.08152432  0.21400889  0.28408198         nan         nan  0.92133394
   0.58837402 -0.1310182          nan  1.                 nan -0.73630651
          nan         nan]
 [        nan         nan         nan         nan         nan         nan
          nan         nan         nan         nan         nan         nan
          nan         nan]
 [-0.11043393  0.15930796 -0.53105095         nan         nan -0.53595756
  -0.44455348  0.48276802         nan -0.73630651         nan  1.
          nan         nan]
 [        nan         nan         nan         nan         nan         nan
          nan         nan         nan         nan         nan         nan
          nan         nan]
 [        nan         nan         nan         nan         nan         nan
          nan         nan         nan         nan         nan         nan
          nan         nan]]
torch.Size([1, 5, 98]) torch.Size([1, 14]) torch.Size([1, 14, 14])
                       Target    Target    Target  Target  Target    Target  \
timestamp
2018-01-01 00:04:00 -0.012524 -0.008999 -0.003718     NaN     NaN -0.011170
2018-01-01 00:05:00 -0.005940 -0.008079 -0.002171     NaN     NaN -0.006154
2018-01-01 00:06:00 -0.005455 -0.004422 -0.009202     NaN     NaN -0.008654
2018-01-01 00:07:00 -0.000644 -0.008873 -0.004458     NaN     NaN -0.012036
2018-01-01 00:08:00 -0.003580 -0.008492 -0.006110     NaN     NaN -0.014178

                       Target    Target  Target    Target  Target    Target  \
timestamp
2018-01-01 00:04:00 -0.002205 -0.028899     NaN -0.002556     NaN -0.007299
2018-01-01 00:05:00 -0.001744 -0.030909     NaN  0.000531     NaN -0.010619
2018-01-01 00:06:00 -0.001331 -0.001331     NaN -0.002572     NaN  0.005323
2018-01-01 00:07:00 -0.002983 -0.026319     NaN -0.003973     NaN  0.000548
2018-01-01 00:08:00 -0.004800 -0.050868     NaN -0.009413     NaN -0.024252

                     Target  Target
timestamp
2018-01-01 00:04:00     NaN     NaN
2018-01-01 00:05:00     NaN     NaN
2018-01-01 00:06:00     NaN     NaN
2018-01-01 00:07:00     NaN     NaN
2018-01-01 00:08:00     NaN     NaN
          Target    Target    Target  Target  Target    Target    Target  \
Target  1.000000  0.065179 -0.213382     NaN     NaN -0.213288 -0.383209
Target  0.065179  1.000000 -0.797838     NaN     NaN  0.422244  0.527829
Target -0.213382 -0.797838  1.000000     NaN     NaN  0.209239 -0.012201
Target       NaN       NaN       NaN     NaN     NaN       NaN       NaN
Target       NaN       NaN       NaN     NaN     NaN       NaN       NaN
Target -0.213288  0.422244  0.209239     NaN     NaN  1.000000  0.851848
Target -0.383209  0.527829 -0.012201     NaN     NaN  0.851848  1.000000
Target -0.086500  0.786920 -0.501645     NaN     NaN  0.540899  0.835670
Target       NaN       NaN       NaN     NaN     NaN       NaN       NaN
Target -0.345837  0.197348  0.382768     NaN     NaN  0.907451  0.911761
Target       NaN       NaN       NaN     NaN     NaN       NaN       NaN
Target  0.038118  0.539161 -0.321880     NaN     NaN  0.417861  0.761527
Target       NaN       NaN       NaN     NaN     NaN       NaN       NaN
Target       NaN       NaN       NaN     NaN     NaN       NaN       NaN

          Target  Target    Target  Target    Target  Target  Target
Target -0.086500     NaN -0.345837     NaN  0.038118     NaN     NaN
Target  0.786920     NaN  0.197348     NaN  0.539161     NaN     NaN
Target -0.501645     NaN  0.382768     NaN -0.321880     NaN     NaN

In [ ]:
a.squeeze()

In [76]:
len(dataset)

1956782

In [81]:
pd.DataFrame(np.random.random((4, 3))).values

array([[0.21048091, 0.07814175, 0.21098803],
       [0.88533118, 0.63138025, 0.91717235],
       [0.03144147, 0.22048096, 0.1377318 ],
       [0.46196295, 0.21895655, 0.89900687]])

In [22]:
def test():
    print('something')

In [24]:
func = eval('test')
func()

something